### ISSUE TITLE
Labels for wopi-client pods

### ISSUE THREAD

**Issue by jglasbergen** [genofire/collaboraonline-helm#2]
Hi there,

I need to add labels to the wopi-client pods in order to make the network policies work. Can you explain where and how to do this in the values.yaml file?

**Comment by genofire** [comment]
please use the official helm-chart:
https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm/collabora-online

There I have added this feature recently:
https://github.com/CollaboraOnline/online/pull/9240

**Comment by genofire** [comment]
You can consume it as helmrepo:
```
helm repo add collabora https://collaboraonline.github.io/online/
helm install collabora-online collabora/collabora-online
```

Or oci:
```
helm install collabora-online oci://ghcr.io/collaboraonline/charts/collabora-online --version 1.1.17
```
From:
  - github https://github.com/CollaboraOnline/online/pkgs/container/charts%2Fcollabora-online
  - docherhub https://hub.docker.com/r/collabora/collabora-online

**Comment by jglasbergen** [comment]
I added the podLabels and run the upgrade. But I don't see the label on the pods.
I assume I did not put it i te right place, her is my values.yaml:

```yaml
collabora:
  aliasgroups:
  - host: http://webapp:8000
  - host: https://test.casereditions.local

  extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:num_prespawn_children=4
  
  server_name: test.casereditions.local
  
  existingSecret:
    enabled: false
    secretName: ""
    usernameKey: "username"
    passwordKey: "password"
  password: adminadmin
  username: admin
  env: []

autoscaling:
  minReplicas: 1

resources: {}

replicaCount: 1

dynamicConfig:

  ingress:
    hosts:
      - host: test.casereditions.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      hosts:
        - test.casereditions.local
      secretName: test-casereditions

podLabels:
  networking/data.egress: true
  networking/internet.egress: true
  networking/internet.ingress: true
  networking/service.egress: true
  networking/service.gress: true
  networking/webapp.egress: true
  networking/webapp.ingress: true
```
